/// A permutation on `{0, 1, …, n-1}` stored as its image vector.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Permutation {
    image: Vec<u32>,
}

impl Permutation {
    /// Create a permutation from its image vector.
    ///
    /// # Panics
    /// Panics if `image` is not a valid permutation (not a bijection on `{0..n}`).
    pub fn new(image: Vec<u32>) -> Self {
        debug_assert!(Self::is_valid(&image), "invalid permutation");
        Self { image }
    }

    /// The identity permutation on `n` elements.
    pub fn identity(n: usize) -> Self {
        Self {
            image: (0..n as u32).collect(),
        }
    }

    /// The number of elements being permuted.
    pub fn len(&self) -> usize {
        self.image.len()
    }

    /// Whether this permutation acts on zero elements.
    pub fn is_empty(&self) -> bool {
        self.image.is_empty()
    }

    /// The image of `i` under this permutation.
    pub fn apply(&self, i: u32) -> u32 {
        self.image[i as usize]
    }

    /// The image vector as a slice.
    pub fn image(&self) -> &[u32] {
        &self.image
    }

    /// Compose `self` then `other`: the result maps `i → other(self(i))`.
    pub fn compose(&self, other: &Permutation) -> Permutation {
        debug_assert_eq!(self.len(), other.len());
        Permutation {
            image: self.image.iter().map(|&i| other.apply(i)).collect(),
        }
    }

    /// The inverse permutation.
    pub fn inverse(&self) -> Permutation {
        let mut inv = vec![0u32; self.len()];
        for (i, &j) in self.image.iter().enumerate() {
            inv[j as usize] = i as u32;
        }
        Permutation { image: inv }
    }

    /// Decompose into disjoint cycles. Each cycle is a `Vec<u32>` starting
    /// from its smallest element. Fixed points are included as length-1 cycles.
    pub fn cycles(&self) -> Vec<Vec<u32>> {
        let n = self.len();
        let mut visited = vec![false; n];
        let mut result = Vec::new();
        for start in 0..n {
            if visited[start] {
                continue;
            }
            let mut cycle = Vec::new();
            let mut cur = start as u32;
            loop {
                visited[cur as usize] = true;
                cycle.push(cur);
                cur = self.apply(cur);
                if cur == start as u32 {
                    break;
                }
            }
            result.push(cycle);
        }
        result
    }

    /// The cycle type: a sorted (ascending) list of cycle lengths.
    pub fn cycle_type(&self) -> Vec<usize> {
        let mut lengths: Vec<usize> = self.cycles().iter().map(|c| c.len()).collect();
        lengths.sort_unstable();
        lengths
    }

    fn is_valid(image: &[u32]) -> bool {
        let n = image.len();
        let mut seen = vec![false; n];
        for &v in image {
            if (v as usize) >= n || seen[v as usize] {
                return false;
            }
            seen[v as usize] = true;
        }
        true
    }
}

/// Generate all elements of the group generated by `generators` starting from `identity`.
pub fn generate_group_elements<T, F>(identity: T, generators: &[T], mut compose: F) -> Vec<T>
where
    T: Clone + std::cmp::Eq + std::hash::Hash,
    F: FnMut(&T, &T) -> T,
{
    use std::collections::HashSet;

    let mut elements: HashSet<T> = HashSet::new();
    elements.insert(identity.clone());

    let mut queue: Vec<T> = vec![identity];
    while let Some(g) = queue.pop() {
        for generator in generators {
            let product = compose(&g, generator);
            if elements.insert(product.clone()) {
                queue.push(product);
            }
        }
    }
    elements.into_iter().collect()
}

/// Generate all elements of the group generated by `generators` on `n` points.
/// Returns the group as a deduplicated `Vec<Permutation>` (including the identity).
pub fn generate_group(n: usize, generators: &[Permutation]) -> Vec<Permutation> {
    generate_group_elements(Permutation::identity(n), generators, |a, b| a.compose(b))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_is_identity() {
        let id = Permutation::identity(5);
        for i in 0..5u32 {
            assert_eq!(id.apply(i), i);
        }
    }

    #[test]
    fn compose_and_inverse() {
        // (0 1 2) -> (1 2 0)
        let p = Permutation::new(vec![1, 2, 0]);
        let inv = p.inverse();
        let id = p.compose(&inv);
        assert_eq!(id, Permutation::identity(3));

        let id2 = inv.compose(&p);
        assert_eq!(id2, Permutation::identity(3));
    }

    #[test]
    fn cycles_3_cycle() {
        let p = Permutation::new(vec![1, 2, 0]);
        let cycles = p.cycles();
        assert_eq!(cycles, vec![vec![0, 1, 2]]);
    }

    #[test]
    fn cycles_transposition_and_fixed() {
        // (0 1)(2) on 3 elements
        let p = Permutation::new(vec![1, 0, 2]);
        let mut cycles = p.cycles();
        cycles.sort_by_key(|c| c[0]);
        assert_eq!(cycles, vec![vec![0, 1], vec![2]]);
    }

    #[test]
    fn cycle_type_sorted() {
        // (0 1 2)(3 4) on 5 elements
        let p = Permutation::new(vec![1, 2, 0, 4, 3]);
        assert_eq!(p.cycle_type(), vec![2, 3]);
    }

    #[test]
    fn generate_cyclic_group() {
        // C_4 generated by (0 1 2 3)
        let rot = Permutation::new(vec![1, 2, 3, 0]);
        let group = generate_group(4, &[rot]);
        assert_eq!(group.len(), 4);
    }

    #[test]
    fn generate_symmetric_s3() {
        // S_3 generated by (0 1 2) and (0 1)
        let r = Permutation::new(vec![1, 2, 0]);
        let s = Permutation::new(vec![1, 0, 2]);
        let group = generate_group(3, &[r, s]);
        assert_eq!(group.len(), 6);
    }

    #[test]
    fn generate_dihedral_d4() {
        // D_4 generated by rotation (0 1 2 3) and reflection (0 3)(1 2)
        let r = Permutation::new(vec![1, 2, 3, 0]);
        let s = Permutation::new(vec![3, 2, 1, 0]);
        let group = generate_group(4, &[r, s]);
        assert_eq!(group.len(), 8);
    }
}
